### ISSUE TITLE
Needs More Clarity On Licensing

### ISSUE THREAD

**Issue by nephatrine** [Paril/quake2-source-archive#1]
There is a GPL license file in the root of the repo, but it looks like some sources (like xsrc and rsrc) are in there that I don't think were ever released under the GPL. It is probably a good idea to make it very clear which mods are available under the GPL and which are under the old id mod license.

**Comment by Paril** [comment]
Good idea. Going to delete LICENSE and put a LICENSE file in each folder to specify which are which.
