### ISSUE TITLE
Quake2 add a melee weapon

### ISSUE THREAD

**Issue by raptus84** [Paril/quake2-source-archive#2]
Hi Paril,
I hope you are the same user from moddb site. I tried to follow your tutorial about creating a melee weapon in Quake2 but I found that some code lines are missing (I was able to find only a Visual Studio 2015 version of Q2 source code).
If you have already done this small mod with your Q2 code, can you send it to me (or to us, I think that it could be cool for the community)?
Thank you for reply
regards

**Comment by Paril** [comment]
Hi there.

That tutorial is quite old and busted - if I recall, it was mainly a copypasta from the Ground Zero/Rogue mission pack anyways. Most of the relevant code is in here: https://github.com/Paril/quake2-source-archive/tree/main/sources/rogue - fire_player_melee is the main entry point if I recall
